/**
 * models/Informe.js
 * ─────────────────────────────────────────────────────────────────────────
 * Domain model for "Informe" (a saved monthly report snapshot for one
 * Cliente/period, including the rendered HTML and the raw section data).
 *
 * See docs/MODEL.md for the full entity/field reference.
 */
import { DB, saveDB } from './db';

/** Returns every Informe record. */
export function getInfs() {
  return DB.infs;
}

/** Returns all informes for a given period (format `YYYY-MM`). */
export function getInfsForPeriodo(per) {
  return DB.infs.filter(i => i.per === per);
}

/** Returns all informes for a given Cliente + period. */
export function getInfsForCliPeriodo(cliId, per) {
  return DB.infs.filter(i => i.cliId === cliId && i.per === per);
}

/** Returns all informes for a given Cliente. */
export function getInfsForCli(cliId) {
  return DB.infs.filter(i => i.cliId === cliId);
}

/** Number of informes generated for a given Cliente. */
export function getInfCountForCli(cliId) {
  return DB.infs.filter(i => i.cliId === cliId).length;
}

/** Number of informes generated by a given Ejecutivo. */
export function getInfCountForEj(ejId) {
  return DB.infs.filter(i => i.ejId === ejId).length;
}

/** Saves a new Informe snapshot (informes are append-only / immutable). */
export function saveInf(data) {
  if (!data.id) data.id = 'i' + Date.now();
  if (!data.ts) data.ts = new Date().toISOString();
  DB.infs.push(data);
  saveDB();
  return data;
}

/** Deletes an Informe by id. */
export function deleteInf(id) {
  DB.infs = DB.infs.filter(i => i.id !== id);
  saveDB();
}

/** Updates rating/feedback for an Informe. */
export function updateInfRating(id, rating, feedback) {
  const inf = DB.infs.find(i => i.id === id);
  if (inf) { inf.rating = rating; inf.feedback = feedback; inf.ratedAt = new Date().toISOString(); saveDB(); }
  return inf;
}

/** Updates an Informe generically (for migrations). */
export function updateInf(id, patch) {
  const inf = DB.infs.find(i => i.id === id);
  if (inf) { Object.assign(inf, patch); saveDB(); }
  return inf;
}
